<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- Pacotes do Entity Framework -->
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />

		<!-- Pacotes do Identity -->
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
		<!-- Binder necessário para IConfiguration.GetValue<T>() -->
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FourPrime.Domain\FourPrime.Domain.csproj" />
		<ProjectReference Include="..\FourPrime.Application\FourPrime.Application.csproj" />
	</ItemGroup>

</Project>